# Dockerfile.streamlit_app
FROM python:3.8
WORKDIR /app
COPY . /app
RUN pip install poetry
RUN poetry config virtualenvs.create false --local
RUN poetry install

EXPOSE 8501
ENTRYPOINT [ "poetry", "run", "streamlit", "run", "rafa/streamlit_app/friday.py"]