version: '3'
services:
  intermediary_server:
    build:
      context: .
      dockerfile: Dockerfile.intermediary_server
    ports:
      - "5001:5001"
    networks:
      - rafa-network

  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit_app
    ports:
      - "8501:8501"
    networks:
      - rafa-network
      
  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    ports:
      - "8080:5002"
    networks:
      - rafa-network
      
  ollama-container:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/ollama
    ports:
      - "11434:11434"
    networks:
      - rafa-network

networks:
  rafa-network:
    driver: bridge