# Dockerfile.intermediary_server
FROM python:3.8
WORKDIR /app
COPY . /app
RUN pip install poetry
RUN poetry install
CMD ["poetry", "run", "python3", "rafa/intermediary_server/http_websocket_bridge.py"]